In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
df=pd.read_csv(r'C:\Users\salon\OneDrive\Desktop\data science\6-months-data-science\machine learning\bike project\Data\Used_Bikes.csv')

In [3]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [4]:
df.head()   ##used to show only top values of the dataset

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [5]:
df.tail(10)  ##used to show only last 10 values of the dataset

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [6]:
df.info()  ##used to show the information about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [7]:
df.columns  ##used to show the columns of the dataset

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [8]:
df[['brand']]  ##used to show the specific column of the dataset

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [9]:
df[['price']]  ##used to show the specific column of the dataset

          price
0       35000.0
1      119900.0
2      600000.0
3       65000.0
4       80000.0
...         ...
32643   39000.0
32644   30000.0
32645   60000.0
32646   15600.0
32647   22000.0

[32648 rows x 1 columns]

In [10]:
df[['city']]

            city
0      Ahmedabad
1          Delhi
2          Delhi
3      Bangalore
4      Bangalore
...          ...
32643      Delhi
32644     Karnal
32645      Delhi
32646     Jaipur
32647       Pune

[32648 rows x 1 columns]

In [11]:
df.bike_name  ##used to show the specific column of the dataset

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [12]:
df.owner

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4        First Owner
            ...
32643    First Owner
32644    First Owner
32645    First Owner
32646    First Owner
32647    First Owner
Name: owner, Length: 32648, dtype: str

In [13]:
df.brand

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [14]:
df['owner']

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4        First Owner
            ...
32643    First Owner
32644    First Owner
32645    First Owner
32646    First Owner
32647    First Owner
Name: owner, Length: 32648, dtype: str

In [15]:
df['owner'].unique() ##used to show the unique values of the specific column of the dataset

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [16]:
df['owner'].nunique()  ##used to show the number of unique values of the specific column of the dataset

4

In [17]:
df['brand'].nunique()

23

In [18]:
df['brand'].nunique()

23

In [19]:
df['brand'].value_counts() ##used to show the count of unique values of the specific column of the dataset

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [20]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [21]:
df.duplicated().sum()

np.int64(25324)

In [22]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [23]:
df.duplicated().sum()

np.int64(25324)

In [24]:
df.drop_duplicates(inplace=True)

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [27]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [28]:
# df.dropna(inplace=True)  ## null value ko drop karne ke liye use hota hai. inplace=True se original dataframe me changes ho jate hai.

In [29]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [30]:
owner_dct={'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}
df['owner']=df['owner'].map(owner_dct)

In [31]:
df['owner'].unique()

array([1, 2, 3, 4])

In [32]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,Bajaj

In [33]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [34]:
brand_dct={'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23}
df['brand']=df['brand'].map(brand_dct)

In [35]:
df['brand'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [36]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,4
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,6
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,7
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,15
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,7
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,7

In [37]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [38]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [39]:
df.drop_duplicates(inplace=True)

In [40]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7306 rows x 6 columns]

In [41]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [42]:
x=df.drop('price',axis=1)

In [43]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      6
9369     60000.0      1  9.0  220.0      7
9370      3430.0      1  4.0  750.0     15
9371     21300.0      1  4.0  400.0      7
9372      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [44]:
y=df['price']

In [45]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
9362     25000.0
9369     35000.0
9370    450000.0
9371    139000.0
9372     80000.0
Name: price, Length: 7306, dtype: float64

In [46]:
df.to_csv("clean_bike_data.csv")